// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Connections struct {
	UserA     string    `json:"user_a"`
	UserB     string    `json:"user_b"`
	CreatedAt time.Time `json:"created_at"`
	Status    int16     `json:"status"`
}

type Follows struct {
	FollowerID string    `json:"follower_id"`
	FolloweeID string    `json:"followee_id"`
	CreatedAt  time.Time `json:"created_at"`
	Status     int16     `json:"status"`
}

type PostMedia struct {
	ID        uuid.UUID             `json:"id"`
	PostID    uuid.UUID             `json:"post_id"`
	Url       string                `json:"url"`
	MediaType string                `json:"media_type"`
	Width     sql.NullInt32         `json:"width"`
	Height    sql.NullInt32         `json:"height"`
	SizeBytes sql.NullInt64         `json:"size_bytes"`
	Meta      pqtype.NullRawMessage `json:"meta"`
	SortIndex sql.NullInt32         `json:"sort_index"`
	CreatedAt time.Time             `json:"created_at"`
}

type Posts struct {
	ID             uuid.UUID             `json:"id"`
	AuthorID       string                `json:"author_id"`
	Content        string                `json:"content"`
	ContentHtml    sql.NullString        `json:"content_html"`
	Visibility     int16                 `json:"visibility"`
	ReplyToPostID  uuid.NullUUID         `json:"reply_to_post_id"`
	OriginalPostID uuid.NullUUID         `json:"original_post_id"`
	Language       sql.NullString        `json:"language"`
	Meta           pqtype.NullRawMessage `json:"meta"`
	LikesCount     int64                 `json:"likes_count"`
	CommentsCount  int64                 `json:"comments_count"`
	SharesCount    int64                 `json:"shares_count"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	SearchVector   interface{}           `json:"search_vector"`
}
