// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUserPosts(ctx context.Context, authorID string) (int64, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connections, error)
	CreateFollow(ctx context.Context, arg CreateFollowParams) (Follows, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Posts, error)
	CreatePostMedia(ctx context.Context, arg CreatePostMediaParams) (PostMedia, error)
	DeleteConnection(ctx context.Context, arg DeleteConnectionParams) (Connections, error)
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) (Follows, error)
	DeletePost(ctx context.Context, id uuid.UUID) (Posts, error)
	DeletePostMedia(ctx context.Context, id uuid.UUID) (PostMedia, error)
	GetPost(ctx context.Context, id uuid.UUID) (Posts, error)
	GetPostMedia(ctx context.Context, postID uuid.UUID) ([]PostMedia, error)
	GetUserConnections(ctx context.Context, userA string) ([]Connections, error)
	GetUserFollows(ctx context.Context, followerID string) ([]Follows, error)
	ListUserPostsAfter(ctx context.Context, arg ListUserPostsAfterParams) ([]Posts, error)
	ListUserPostsFirstPage(ctx context.Context, arg ListUserPostsFirstPageParams) ([]Posts, error)
	ListUserPostsOffset(ctx context.Context, arg ListUserPostsOffsetParams) ([]Posts, error)
	UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connections, error)
	UpdateFollow(ctx context.Context, arg UpdateFollowParams) (Follows, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Posts, error)
}

var _ Querier = (*Queries)(nil)
